### ISSUE TITLE
Add "trap" instruction at the end of the program

### ISSUE THREAD

**Issue by piotrzwolinski** [FluffyLabs/typeberry-toolkit#52]

**Comment by tomusdrw** [comment]
CC @mateuszsikora - can you confirm that there is a "TRAP" instruction at the very end of every program?

**Comment by mateuszsikora** [comment]
> CC @mateuszsikora - can you confirm that there is a "TRAP" instruction at the very end of every program?

A correct program should have dynamic jump to 0xffff0000 at the end. If there is no dynamic jump at the end then pvm will look for a next instruction that doesn't exist so it will be a "TRAP"

**Comment by tomusdrw** [comment]
Currently it seems that "Run"ning a program in the debugger always ends in `PANIC` state, while it should actually end with a `trap`, since the programs from test JSONs don't have that dynamic jump at the end. Am I understanding this right?

I think we should display a grayed-out `TRAP` at the end of the debugger so that when we step over the last instruction we can actually still display something that looks correct (i.e. that we terminated at this trap).

**Comment by mateuszsikora** [comment]
> Currently it seems that "Run"ning a program in the debugger always ends in PANIC state, while it should actually end with a trap, since the programs from test JSONs don't have that dynamic jump at the end. Am I understanding this right?

correct. there is one test `inst_ret_halt.json` that has that dynamic jump at the end and in this case the final status should be `HALT`.

> I think we should display a grayed-out TRAP at the end of the debugger so that when we step over the last instruction we can actually still display something that looks correct (i.e. that we terminated at this trap).

I think we can show it when this implicit `TRAP` happen. if the program is correct then it is not needed

**Comment by tomusdrw** [comment]
Fixed via #83
